// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB16Nwd015abeS7YDUjNMxa4rQag-7hVb4',
    appId: '1:415963763367:web:b5c00214eb81b475a00182',
    messagingSenderId: '415963763367',
    projectId: 'flutter-firebase-rtdb-concept',
    authDomain: 'flutter-firebase-rtdb-concept.firebaseapp.com',
    storageBucket: 'flutter-firebase-rtdb-concept.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAA5Yu3Hqkdjtx2n_IgCz82Y98hTP9Oo',
    appId: '1:415963763367:android:020f6da7431396e8a00182',
    messagingSenderId: '415963763367',
    projectId: 'flutter-firebase-rtdb-concept',
    storageBucket: 'flutter-firebase-rtdb-concept.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTLxVMFytXhb0EqbZd6hKZl83JaUV15U',
    appId: '1:415963763367:ios:bd1f2bc7cc6fdcf5a00182',
    messagingSenderId: '415963763367',
    projectId: 'flutter-firebase-rtdb-concept',
    storageBucket: 'flutter-firebase-rtdb-concept.appspot.com',
    iosClientId: '415963763367-upg2ecdbea9b55dahg3cvmtm9j08hftr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRtdbConcept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqTLxVMFytXhb0EqbZd6hKZl83JaUV15U',
    appId: '1:415963763367:ios:3342579a4d3e457ea00182',
    messagingSenderId: '415963763367',
    projectId: 'flutter-firebase-rtdb-concept',
    storageBucket: 'flutter-firebase-rtdb-concept.appspot.com',
    iosClientId: '415963763367-q3morenh10fa2sita5aunbihhfnktpvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRtdbConcept.RunnerTests',
  );
}
